services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"

    env_file:
      - .env 

    volumes:
      - ./node_modules:/src/node_modules 
      - ./uploads:/src/uploads  

    command: ["node", "dist/app.js"]  

volumes:
  db-data:

#   services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     ports:
#       - "8080:8080"
#     env_file:
#       - .env 
#     volumes:
#       - ./node_modules:/src/node_modules 
#       - ./uploads:/src/uploads  
#     command: ["node", "dist/app.js"]

#   nginx:
#     image: nginx:alpine
#     container_name: nginx-reverse-proxy
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/letsencrypt:/etc/letsencrypt # If using SSL certificates
 
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - backend
#     restart: always

# volumes:
#   db-data:

